name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: bun install

      - name: Create test env file
        run: |
          echo "TEST_DATABASE_CLIENT=pglite" > packages/core/.env.test
          echo "NODE_ENV=test" >> packages/core/.env.test

      - name: Run tests
        run: cd packages/core && bun test:coverage

      - name: Check format
        run: bun run format:check

      - name: Run lint
        run: bun run lint

      - name: Build packages
        run: bun run build && bun run build:docs

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
